apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: k8s-infra
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: infra/gitops/argocd-apps/k8s-infra
    repoURL: 'https://github.com/kotjiac/mlp-tcc.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
