apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  # O destino da sua instalação Kubeflow
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: default
  
  # A fonte no seu Git, que usa o overlay 'example' do Kustomize.
  # Isso está correto e vai aplicar seus patches (como o do nodeSelector).
  source:
    path: infra/gitops/argocd-apps/kubeflow/manifests/example
    repoURL: 'https://github.com/kotjiac/mlp-tcc.git'
    targetRevision: master
    
  # --- POLÍTICA DE SINCRONIZAÇÃO COMPLETA ---
  # Inclui automação e a política de retry que adicionamos
  # para tornar a instalação mais robusta.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5 
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m

  # --- OPÇÕES DE SINCRONIZAÇÃO CORRIGIDAS E FINAL ---
  # Esta é a parte crucial que faltava novamente.
  # Replace=true é a estratégia agressiva que evita o erro "metadata.annotations: Too long".
  syncOptions:
    - CreateNamespace=true
    - Replace=true