apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      containers:
      - name: ml-pipeline-api-server
        envFrom:
        - configMapRef:
            name: pipeline-api-server-config
        env:
        - name: KUBEFLOW_USERID_HEADER
          value: kubeflow-userid
        - name: KUBEFLOW_USERID_PREFIX
          value: ""
