# patches/viz-server-nodeselector.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-visualizationserver
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64